### ISSUE TITLE
cannot access teaser video

### ISSUE THREAD

**Issue by trimbandaru** [SAP-samples/btp-cap-dox-invoice-validation#3]
Hi Team,

The link https://video.sap.com/media/t/1_cma51zr3 to teaser video not working with S/P user credentials.
can you make this public or upload to youtube channel?

Thanks
-Trim

**Comment by RobinPurschwitz** [comment]
Hi,
video link needs to be updated to https://sapvideo.cfapps.eu10-004.hana.ondemand.com/?entry_id=1_cma51zr3
If thats done, it should work.
